### ISSUE TITLE
I get IPFS module not found no fresh install

### ISSUE THREAD

**Issue by Gozala** [RangerMauve/webrun#27]
```
webrun
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'ipfs'
Require stack:
- /Users/gozala/Projects/archivist/node_modules/@rangermauve/webrun/src/plugins/ipfs.js
- /Users/gozala/Projects/archivist/node_modules/@rangermauve/webrun/src/index.js
- /Users/gozala/Projects/archivist/node_modules/@rangermauve/webrun/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gozala/Projects/archivist/node_modules/@rangermauve/webrun/src/plugins/ipfs.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/gozala/Projects/archivist/node_modules/@rangermauve/webrun/src/plugins/ipfs.js',
    '/Users/gozala/Projects/archivist/node_modules/@rangermauve/webrun/src/index.js',
    '/Users/gozala/Projects/archivist/node_modules/@rangermauve/webrun/bin/cli.js'
  ]
}
```

**Comment by RangerMauve** [comment]
Were there any error during install? It should be loading js-ipfs. Though stuff may have broken since I last visited this module. 😰

**Comment by Gozala** [comment]
I have not noticed any errors during install, but I was not paying attention to be honest. For what it's worth I would really like if plugins like Dat or IPFS where things you could add instead of having those baked inn.

All I really want I suppose is a drop-in replacement for https://deno.land/.

**Comment by RangerMauve** [comment]
Yeah! I agree. I was thinking it'd be cool to have a list of `webrun-plugin-*`s that the default would attempt to load and ignore silent fails.

**Comment by RangerMauve** [comment]
You know what. I can't focus on real work right now so I'll spend a bit of time getting that together to warm up. 💜

**Comment by RangerMauve** [comment]
Making progress on this. Try version 3.0.2 in the meantime.

**Comment by RangerMauve** [comment]
K, I've taken out the IPFS and Dat plugins into separate modules.

https://github.com/RangerMauve/webrun-plugin-ipfs
https://github.com/RangerMauve/webrun-plugin-dat

Try installing version 4.0.0. 😁
